import { CareMockData } from "@/lib/mock-types";
import { PLAN_CATALOG } from "@/lib/plans";

export const careMockData: CareMockData = {
  usuarios: [
    {
      id: "u-tutor-1",
      nombre: "Ana",
      apellido: "Martínez",
      email: "ana@care.com",
      telefono: "+54 11 4000-1112",
      rol: "tutor",
    },
    {
      id: "u-persona-1",
      nombre: "Rosa",
      apellido: "Martínez",
      email: "rosa@care.com",
      telefono: "+54 11 4000-1111",
      rol: "persona-cuidada",
    },
    {
      id: "u-cuidador-1",
      nombre: "Laura",
      apellido: "Sosa",
      email: "laura@care.com",
      telefono: "+54 11 4555-9090",
      rol: "cuidador",
    },
    {
      id: "u-prof-1",
      nombre: "Lucía",
      apellido: "Ferraro",
      email: "lferraro@clinica.com",
      telefono: "+54 11 4222-8877",
      rol: "profesional",
    },
    {
      id: "u-prov-1",
      nombre: "Carlos",
      apellido: "Suárez",
      email: "ventas@casasegura.com",
      telefono: "+54 11 4999-1212",
      rol: "proveedor",
    },
    {
      id: "u-admin-1",
      nombre: "CARE",
      apellido: "Admin",
      email: "admin@care.com",
      telefono: "+54 11 4111-0000",
      rol: "admin",
    },
  ],
  personasCuidadas: [
    {
      nombre: "Rosa",
      apellido: "Martínez",
      dni: "18.234.987",
      fechaNacimiento: "1947-05-12",
      domicilio: "Av. Siempre Viva 123",
      localidad: "CABA",
      provincia: "Buenos Aires",
      telefono: "+54 11 4000-1111",
      observacionesGenerales: "Prefiere visitas por la mañana. Usa audífonos.",
      medicoCabecera: "Dra. Lucía Ferraro",
      diagnosticosRelevantes: "Hipertensión controlada. Artrosis.",
      alergias: "Penicilina.",
      restricciones: "No subir escaleras sin asistencia.",
      movilidad: "Con bastón y acompañamiento parcial.",
      necesitaAcompanamiento: true,
      observacionesMedicas: "Control cardiológico cada 6 meses.",
      obraSocialTipo: "Prepaga",
      obraSocialNombre: "OSDE",
      obraSocialPlan: "210",
      numeroAfiliado: "OSD-994881",
      telefonoUtil: "0800-333-6733",
      credencialAdjunta: "credencial_osde_rosa.pdf",
      tutores: [
        { id: "t1", nombre: "Ana Martínez", rol: "principal", permisos: "administrador" },
        { id: "t2", nombre: "Jorge Martínez", rol: "secundario", permisos: "agenda" },
      ],
      cuidadores: [
        { id: "c1", nombre: "Laura Sosa", rol: "Cuidadora diurna", horarios: "Lun a Vie 08:00-16:00", contacto: "+54 11 4555-9090" },
        { id: "c2", nombre: "Mario Díaz", rol: "Cuidador nocturno", horarios: "Sab y Dom 20:00-08:00", contacto: "+54 11 4222-3030" },
      ],
      contactosEmergencia: [
        { id: "e1", nombre: "Ana Martínez", relacion: "Hija", telefono: "+54 11 4000-1112", whatsapp: "+54 11 4000-1112", email: "ana@care.com" },
        { id: "e2", nombre: "Dr. Pérez", relacion: "Médico", telefono: "+54 11 4000-2222", whatsapp: "+54 11 4000-2222", email: "drperez@clinica.com" },
      ],
      documentacion: [
        { id: "d1", tipo: "DNI", archivo: "dni_rosa_frente.pdf", actualizado: "2026-01-10" },
        { id: "d2", tipo: "CUD", archivo: "cud_2026.pdf", actualizado: "2026-02-02" },
        { id: "d3", tipo: "Recetas", archivo: "receta_hipertension.pdf", actualizado: "2026-04-14" },
        { id: "d4", tipo: "Estudios", archivo: "estudio_ecodoppler.pdf", actualizado: "2026-03-05" },
        { id: "d5", tipo: "Autorizaciones", archivo: "autorizacion_traslado.pdf", actualizado: "2026-04-01" },
        { id: "d6", tipo: "Otros documentos", archivo: "historia_clinica_resumen.pdf", actualizado: "2026-01-20" },
      ],
    },
  ],
  cuidadores: {
    perfiles: [
      {
        id: "c-1",
        foto: "LS",
        nombre: "Laura Sosa",
        tier: "premium",
        telefonoContacto: "+54 11 4000-2001",
        whatsappContacto: "+54 11 4000-2001",
        zonasTrabajo: ["CABA", "Buenos Aires Norte"],
        localidad: "Belgrano",
        modalidades: ["Con retiro", "Por hora", "Noches"],
        disponibilidadEspecial: ["Sábados", "Domingos"],
        experiencia: 8,
        tareas: ["Adultos mayores", "Administración de medicación", "Compañía"],
        calificacion: 4.8,
        perfilCompleto: true,
        referenciasCargadas: true,
        referenciasVerificadas: true,
        recomendadoCare: true,
        datosActualizados: true,
        estadoActualizacionPerfil: "datos-actualizados",
        altaDisponibilidad: true,
        ultimaActualizacion: "2026-05-01",
        recomendacionesCount: 0,
        recomendacionesPromedio: 0,
      },
      {
        id: "c-2",
        foto: "MD",
        nombre: "Mario Díaz",
        tier: "destacado",
        whatsappContacto: "+54 11 4333-2002",
        zonasTrabajo: ["Buenos Aires Oeste", "La Plata"],
        localidad: "Ramos Mejía",
        modalidades: ["Sin retiro", "Jornada completa", "Guardia 24 hs"],
        disponibilidadEspecial: ["Feriados", "Fines de semana completos"],
        experiencia: 5,
        tareas: ["Movilidad reducida", "Higiene personal", "Control de signos vitales"],
        calificacion: 4.4,
        perfilCompleto: true,
        referenciasCargadas: true,
        referenciasVerificadas: false,
        recomendadoCare: false,
        datosActualizados: true,
        estadoActualizacionPerfil: "pendiente-actualizacion",
        altaDisponibilidad: false,
        ultimaActualizacion: "2026-04-22",
        recomendacionesCount: 0,
        recomendacionesPromedio: 0,
      },
      {
        id: "c-3",
        foto: "CR",
        nombre: "Carla Ríos",
        tier: "basico",
        zonasTrabajo: ["CABA", "Buenos Aires Sur"],
        localidad: "Caballito",
        modalidades: ["Con retiro", "Reemplazos", "Por hora"],
        disponibilidadEspecial: ["Noches", "Algunos fines de semana"],
        experiencia: 3,
        tareas: ["Acompañamiento a turnos", "Preparación de comidas", "Tareas del hogar livianas"],
        calificacion: 4.1,
        perfilCompleto: false,
        referenciasCargadas: true,
        referenciasVerificadas: false,
        recomendadoCare: false,
        datosActualizados: false,
        estadoActualizacionPerfil: "datos-vencidos",
        altaDisponibilidad: true,
        ultimaActualizacion: "2026-03-10",
        recomendacionesCount: 0,
        recomendacionesPromedio: 0,
      },
    ],
    recomendaciones: [
      {
        id: "r1",
        caregiverId: "c-1",
        cuidadorSeleccionado: "Laura Sosa",
        personaQueRecomienda: "Ana Martínez",
        periodoDesde: "2025-01-01",
        periodoHasta: "2026-04-30",
        zonaServicio: "Belgrano - CABA",
        modalidadServicio: "Con retiro",
        tareasRealizadas: "Medicación, compañía y acompañamiento a turnos.",
        calificacionGeneral: 5,
        puntualidad: 5,
        tratoHumano: 5,
        responsabilidad: 5,
        comunicacion: 4,
        confiabilidad: 5,
        comentario: "Excelente trato y mucha responsabilidad.",
        loVolveriaAContratar: true,
        autorizaMostrarRecomendacion: true,
        autorizaContactoReferencia: true,
        status: "aprobada",
      },
      {
        id: "r2",
        caregiverId: "c-2",
        cuidadorSeleccionado: "Mario Díaz",
        personaQueRecomienda: "Jorge Pérez",
        periodoDesde: "2025-03-01",
        periodoHasta: "2026-02-15",
        zonaServicio: "Ramos Mejía",
        modalidadServicio: "Guardia 24 hs",
        tareasRealizadas: "Control de signos vitales e higiene personal.",
        calificacionGeneral: 4,
        puntualidad: 4,
        tratoHumano: 4,
        responsabilidad: 4,
        comunicacion: 4,
        confiabilidad: 4,
        comentario: "Buen desempeño general.",
        loVolveriaAContratar: true,
        autorizaMostrarRecomendacion: true,
        autorizaContactoReferencia: false,
        status: "pendiente-revision",
      },
      {
        id: "r3",
        caregiverId: "c-3",
        cuidadorSeleccionado: "Carla Ríos",
        personaQueRecomienda: "Lucía Gómez",
        periodoDesde: "2025-11-01",
        periodoHasta: "2026-01-30",
        zonaServicio: "Caballito",
        modalidadServicio: "Por hora",
        tareasRealizadas: "Compañía y apoyo liviano en el hogar.",
        calificacionGeneral: 3,
        puntualidad: 3,
        tratoHumano: 4,
        responsabilidad: 3,
        comunicacion: 3,
        confiabilidad: 3,
        comentario: "No se adaptó totalmente a horarios requeridos.",
        loVolveriaAContratar: false,
        autorizaMostrarRecomendacion: true,
        autorizaContactoReferencia: false,
        status: "rechazada",
      },
    ],
    recordatoriosActualizacion: [
      {
        caregiverId: "c-1",
        caregiverNombre: "Laura Sosa",
        estadoActualizacionPerfil: "datos-actualizados",
        ultimaActualizacionPerfil: "2026-05-01",
        ultimoRecordatorioWhatsApp: "2026-05-01 09:00",
        ultimoRecordatorioEmail: "2026-05-01 09:02",
        estadoEnvio: "confirmado",
      },
      {
        caregiverId: "c-2",
        caregiverNombre: "Mario Díaz",
        estadoActualizacionPerfil: "pendiente-actualizacion",
        ultimaActualizacionPerfil: "2026-04-22",
        ultimoRecordatorioWhatsApp: "2026-05-01 09:05",
        ultimoRecordatorioEmail: "2026-05-01 09:08",
        estadoEnvio: "enviado",
      },
      {
        caregiverId: "c-3",
        caregiverNombre: "Carla Ríos",
        estadoActualizacionPerfil: "datos-vencidos",
        ultimaActualizacionPerfil: "2026-03-10",
        ultimoRecordatorioWhatsApp: "2026-04-01 09:10",
        ultimoRecordatorioEmail: "2026-04-01 09:13",
        estadoEnvio: "vencido",
      },
    ],
  },
  medicacion: {
    delDia: [
      { id: "d1", nombre: "Losartan", dosis: "1 comprimido", horario: "09:00", estado: "pendiente", responsable: "Laura Sosa" },
      { id: "d2", nombre: "Aspirina", dosis: "100 mg", horario: "14:00", estado: "confirmado-cuidador", responsable: "Ana Martínez" },
      { id: "d3", nombre: "Vitamina D", dosis: "1 cápsula", horario: "20:00", estado: "sin-respuesta", responsable: "Mario Díaz" },
    ],
    activa: [
      {
        id: "a1",
        nombre: "Losartan",
        dosis: "50 mg",
        frecuencia: "Cada 12 horas",
        horarios: "09:00, 21:00",
        fechaInicio: "2026-04-01",
        indicaciones: "Tomar con agua luego del desayuno.",
        fotoMedicamento: "",
        responsableAdministracion: "Laura Sosa",
        requiereConfirmacion: true,
        alertarTutorSiNoConfirma: true,
        tiempoEsperaAlertaMinutos: 30,
        stockActual: 18,
        recordatorioReposicion: 10,
        recetaAsociada: "receta_abril_losartan.pdf",
        activo: true,
      },
      {
        id: "a2",
        nombre: "Aspirina",
        dosis: "100 mg",
        frecuencia: "1 vez por día",
        horarios: "14:00",
        fechaInicio: "2026-02-14",
        fechaFin: "2026-08-14",
        indicaciones: "Tomar después de almorzar.",
        fotoMedicamento: "",
        responsableAdministracion: "Ana Martínez",
        requiereConfirmacion: true,
        alertarTutorSiNoConfirma: false,
        tiempoEsperaAlertaMinutos: 0,
        stockActual: 24,
        recordatorioReposicion: 8,
        recetaAsociada: "receta_cardiologia.pdf",
        activo: true,
      },
    ],
    historial: [
      { id: "h1", fecha: "2026-05-05", horario: "09:00", estado: "tomado", confirmadoPor: "Laura Sosa" },
      { id: "h2", fecha: "2026-05-05", horario: "21:00", estado: "omitido", confirmadoPor: "Sin confirmación" },
      { id: "h3", fecha: "2026-05-04", horario: "14:00", estado: "confirmado-cuidador", confirmadoPor: "Ana Martínez" },
    ],
  },
  agenda: {
    eventos: [
      { id: "ev1", type: "medicacion", titulo: "Tomar Losartan", fecha: "2026-05-06", hora: "09:00", lugar: "Domicilio", personaAsociada: "Rosa Martínez", responsable: "Laura Sosa", estado: "pendiente", notas: "1 comprimido con desayuno.", contactoRelacionado: "Ana Martínez - +54 11 4000-1112" },
      { id: "ev2", type: "turnos-medicos", titulo: "Control cardiológico", fecha: "2026-05-07", hora: "10:30", lugar: "Clínica Central", personaAsociada: "Rosa Martínez", responsable: "Ana Martínez", estado: "confirmado", notas: "Llevar estudios anteriores.", contactoRelacionado: "Recepción - +54 11 4300-2020" },
      { id: "ev3", type: "estudios", titulo: "Laboratorio sangre", fecha: "2026-05-08", hora: "08:00", lugar: "Laboratorio Norte", personaAsociada: "Rosa Martínez", responsable: "Mario Díaz", estado: "urgente", notas: "Ayuno de 8 horas.", contactoRelacionado: "Lab Norte - +54 11 4333-9988" },
      { id: "ev4", type: "terapias", titulo: "Kinesiología", fecha: "2026-05-06", hora: "16:00", lugar: "Centro Kine Activa", personaAsociada: "Rosa Martínez", responsable: "Laura Sosa", estado: "confirmado", notas: "Sesión de 45 minutos.", contactoRelacionado: "Lic. Méndez - +54 11 4555-7890" },
      { id: "ev5", type: "tramites", titulo: "Renovar autorización CUD", fecha: "2026-05-15", hora: "11:00", lugar: "Sede comunal", personaAsociada: "Rosa Martínez", responsable: "Ana Martínez", estado: "pendiente", notas: "Llevar DNI y certificado médico.", contactoRelacionado: "Mesa de ayuda - 147" },
    ],
  },
  marketplace: [
    { id: "v1", foto: "SW", titulo: "Silla de ruedas plegable", categoria: "movilidad", zona: "CABA", estado: "Excelente", precio: "$320.000", tipo: "venta" },
    { id: "v2", foto: "CA", titulo: "Colchón antiescaras premium", categoria: "rehabilitacion", zona: "La Plata", estado: "Nuevo", precio: "$210.000", tipo: "venta" },
    { id: "a1", foto: "CO", titulo: "Cama ortopédica eléctrica", categoria: "descanso", zona: "Buenos Aires Norte", estado: "Muy bueno", precio: "$95.000 / mes", tipo: "alquiler" },
    { id: "a2", foto: "OX", titulo: "Concentrador de oxígeno", categoria: "salud-domiciliaria", zona: "Buenos Aires Oeste", estado: "Muy bueno", precio: "$60.000 / mes", tipo: "alquiler" },
    { id: "i1", foto: "AN", titulo: "Intercambio andador por silla de ducha", categoria: "movilidad", zona: "CABA", estado: "Buen estado", tipo: "intercambio" },
    { id: "i2", foto: "SR", titulo: "Intercambio sesiones de rehabilitación", categoria: "rehabilitacion", zona: "Buenos Aires Sur", estado: "Disponible", tipo: "intercambio" },
    { id: "d1", foto: "BD", titulo: "Donación de barras de apoyo para baño", categoria: "bano", zona: "Interior Buenos Aires", estado: "Muy bueno", tipo: "donaciones" },
    { id: "d2", foto: "PA", titulo: "Solicitud de pañales para adulto", categoria: "insumos", zona: "Resto Argentina", estado: "Urgente", tipo: "donaciones" },
  ] as CareMockData["marketplace"],
  servicios: [
    { id: "s1", nombreProveedor: "Traslados CARE Move", categoria: "traslados-y-acompanamiento", descripcion: "Traslado de personas mayores a turnos médicos, estudios y trámites. Incluye vehículo adaptado y acompañamiento.", zonaCobertura: "CABA y Buenos Aires Norte", telefonoWhatsapp: "+54 11 4555-1010", email: "contacto@caremove.com", plan: "Premium", destacado: true, disponibilidad: "Lunes a domingo 24 hs" },
    { id: "s2", nombreProveedor: "Hogar en Orden Senior", categoria: "desarme-y-organizacion-del-hogar", descripcion: "Desmontaje de vivienda, inventario, embalaje, coordinación de donaciones/venta/descarte y limpieza final.", zonaCobertura: "CABA, Buenos Aires Sur y Oeste", telefonoWhatsapp: "+54 11 4333-7878", email: "equipo@hogarenorden.com", plan: "Destacado", destacado: true, disponibilidad: "Lunes a sábados" },
    { id: "s3", nombreProveedor: "Casa Segura Adaptaciones", categoria: "adaptacion-del-hogar", descripcion: "Instalación de rampas, barrales, baño adaptado y mejoras de seguridad domiciliaria para prevención de caídas.", zonaCobertura: "La Plata e Interior Buenos Aires", telefonoWhatsapp: "+54 11 4999-1212", email: "ventas@casasegura.com", plan: "Basico", destacado: false, disponibilidad: "Lunes a viernes" },
    { id: "s4", nombreProveedor: "Gestiones Senior Plus", categoria: "tramites-y-gestiones", descripcion: "Asistencia con obras sociales, prepagas, CUD, recetas, autorizaciones y documentación médica.", zonaCobertura: "Resto Argentina (remoto y presencial)", telefonoWhatsapp: "+54 11 4222-9900", email: "info@gestionsenior.com", plan: "Destacado", destacado: true, disponibilidad: "Lunes a viernes" },
    { id: "s5", nombreProveedor: "Asistencia Hogar Integral", categoria: "servicios-domiciliarios-complementarios", descripcion: "Limpieza, cocina, lavandería, compras, mantenimiento menor, compañía y asistencia digital domiciliaria.", zonaCobertura: "CABA y Buenos Aires Oeste", telefonoWhatsapp: "+54 11 4777-1313", email: "contacto@hogarintegral.com", plan: "Basico", destacado: false, disponibilidad: "Turnos por hora y jornada completa" },
  ],
  monetizacion: {
    planes: PLAN_CATALOG,
    suscripcionActual: {
      cuenta: "Familia Martínez",
      planNombre: "Familiar Esencial",
      linea: "familias",
      estado: "activa",
      proximoVencimiento: "2026-06-01",
      monto: "$14.900",
      cicloFacturacion: "Mensual",
      notaIntegracion: "Preparado para integrar cobros y renovaciones automáticas con Mercado Pago.",
    },
  },
};
